import {GAME_CONFIG} from "./config";
import {CATS,catById} from "./data/cats";
import {buyDiamondPack,buyPack,collectPond,PACK_COST,pondProduced,rollDiamondRarity,rollRarity,rollShiny,awardDuel} from "./core/economy";
import {loadProgress,saveProgress,STORAGE_KEY,defaultOwned} from "./core/storage";
import {starterDeck,validateDeck} from "./core/deck";
import {chooseOpponentCard,opponentCollection,playRound,startDuel} from "./core/duel";
import type {BattleCard,Cat,DeckCard,DuelState,Progress,Rarity} from "./types";
import {assets,catAsset,preloadAssets} from "./data/assetManifest";

const app=document.querySelector<HTMLDivElement>("#app")!;
let progress=loadProgress(localStorage.getItem(STORAGE_KEY));let screen="island";let opening=false;let logoTaps:number[]=[];let duel:DuelState|null=null;let catsMode:"collection"|"deck"="collection";let selectedBuilding:string|null="pond";let showOdds=false;let selectedCatId:string|null=null;let selectedBattleUid:string|null=null;const enemyCollection=opponentCollection();
const icons=assets.icons;
const art=(c:Cat,locked=false,shiny=false)=>`<div class="cat-art ${locked?"locked":""} ${shiny?"shiny":""}"><img src="${catAsset(c.id,shiny)}" alt="${locked?"Neobjevená kočka":c.name}" draggable="false" /><i class="portrait-glow"></i></div>`;
const ownedTotal=(id:string)=>(progress.collection[id]?.normal||0)+(progress.collection[id]?.shiny||0);
const card=(c:Cat,mode="collection",battle?:BattleCard)=>{const owned=progress.collection[c.id],shiny=battle?.shiny||false;return `<button class="cat-card ${c.rarity.toLowerCase()} ${shiny?"is-shiny":""} ${battle?.uid===selectedBattleUid?"selected":""}" ${battle?`data-play="${battle.uid}"`:`data-cat="${c.id}"`} ${!owned&&mode==="collection"?"disabled":""}>${art(c,!owned,shiny)}<strong>${owned||battle?c.name:"???"}</strong><small>${c.element} · Síla ${c.power} · Lv. ${owned?.level||1}</small>${owned?`<span>${owned.normal}× · ✦${owned.shiny}</span>`:""}</button>`};
function header(){return `<header class="top-bar"><button class="profile"><img src="${assets.ui.frame}" alt="Profil"/><span><small>HVĚZDNÝ CHOVATEL</small><b>Úroveň ${progress.level}</b></span></button><button class="logo">MEOW<span>VERSE</span></button><div class="stats"><span><img src="${icons.fish}" alt="Rybky"/><b>${progress.fish}</b></span><span><img src="${icons.diamond}" alt="Diamanty"/><b>${progress.diamonds}</b></span><button class="settings"><img src="${icons.settings}" alt="Nastavení"/></button></div></header>`;}
function island(){const fish=pondProduced(progress.pondAt);const sheets={pond:`<div><b>Rybník · ${fish}/100</b><small>${fish?`${fish} rybek je připraveno.`:"Další rybka se právě chystá."}</small></div><button class="primary" data-action="collect" ${fish?"":"disabled"}>Vyzvednout rybky</button>`,home:`<div><b>Kočičí domek</b><small>${Object.keys(progress.collection).length} objevených druhů</small></div><button class="secondary" data-nav="cats">Prohlédnout</button>`,arena:`<div><b>Aréna</b><small>${progress.wins} výher · ${progress.losses} proher</small></div><button class="secondary" data-nav="arena">Otevřít</button>`};return `<section class="island"><div class="island-title"><p>KOČIČÍ OSTROV</p><h1>${fish?`${fish} rybek čeká na vyzvednutí`:"Rybník právě vyrábí"}</h1></div><div class="world" data-island-world><div class="floating-land"><i class="path p1"></i><i class="path p2"></i><article class="world-building pond ${selectedBuilding==="pond"?"selected":""}" data-building="pond"><img src="${assets.buildings.pond}" alt="Rybník"/><div class="building-label"><b>Rybník</b><span>${fish}/100</span></div></article><article class="world-building home ${selectedBuilding==="home"?"selected":""}" data-building="home"><img src="${assets.buildings.home}" alt="Kočičí domek"/><div class="building-label"><b>Domek</b><span>${Object.keys(progress.collection).length} druhů</span></div></article><article class="world-building arena-building ${selectedBuilding==="arena"?"selected":""}" data-building="arena"><img src="${assets.buildings.arena}" alt="Aréna"/><div class="building-label"><b>Aréna</b><span>${progress.wins} výher</span></div></article>${["jiskra","kapka","listka"].map((id,i)=>`<div class="wander w${i}">${art(catById(id)!)}</div>`).join("")}</div>${selectedBuilding?`<div class="island-sheet">${sheets[selectedBuilding as keyof typeof sheets]}</div>`:""}</div></section>`;}
function deckStats(){const cards=progress.deck.map(c=>catById(c.catId)!).filter(Boolean);const avg=cards.length?Math.round(cards.reduce((s,c)=>s+c.power,0)/cards.length):0;return `<div class="deck-stats"><span>${progress.deck.length}/20 karet</span><span>Průměr ${avg}</span><span>🔥 ${cards.filter(c=>c.element==="Oheň").length}</span><span>💧 ${cards.filter(c=>c.element==="Voda").length}</span><span>🌿 ${cards.filter(c=>c.element==="Příroda").length}</span><span>✦ ${progress.deck.filter(c=>c.shiny).length}</span></div>`;}
function cats(){const validation=progress.starterDeckActive?{valid:true,errors:[]}:validateDeck(progress.deck,progress.collection);const collectionView=`<div class="filters"><button>Všechny</button><button>Oheň</button><button>Voda</button><button>Příroda</button><button>Shiny</button></div><div class="cat-grid">${CATS.map(c=>card(c)).join("")}</div><button class="primary cats-primary" data-cats-mode="deck">Upravit balíček</button>`;const editorView=`${progress.starterDeckActive?`<div class="notice compact">Používáš výukový balíček.</div>`:""}${deckStats()}<div class="deployed-slot"><b>Nasazená kočka</b><span>${progress.deployed?catById(progress.deployed.catId)?.name:"Nevybrána"}</span></div>${validation.errors.map(e=>`<small class="error">${e}</small>`).join("")}<div class="cat-grid">${CATS.map(c=>{const count=progress.deck.filter(x=>x.catId===c.id).length;return `<article class="editor-card">${card(c)}${progress.collection[c.id]?`<div class="edit"><button data-remove="${c.id}" aria-label="Odebrat">−</button><b>${count}</b><button data-add="${c.id}" aria-label="Přidat">+</button><button data-deploy="${c.id}" aria-label="Nasadit">★</button></div>`:""}</article>`}).join("")}</div><button class="primary cats-primary" data-cats-mode="collection">Uložit balíček</button>`;return `<section><p class="kicker">KOČIČÍ ARCHIV</p><h1>${catsMode==="collection"?"Tvoje sbírka":"Editor balíčku"}</h1><div class="screen-tabs"><button data-cats-mode="collection" class="${catsMode==="collection"?"active":""}">Sbírka</button><button data-cats-mode="deck" class="${catsMode==="deck"?"active":""}">Balíček ${progress.deck.length}/20</button></div>${catsMode==="collection"?collectionView:editorView}</section>`;}
function packs(){return `<section class="packs"><p class="kicker">KOUZELNÁ DÍLNA</p><h1>Kočičí schránka</h1><p>Uvnitř čeká jeden nový společník.</p><div class="chest"><img src="${assets.packs.chest}" alt="Magická kočičí schránka"/></div><div class="pack-price"><img src="${assets.icons.fish}" alt=""/>${progress.freePack?"První otevření zdarma":`${PACK_COST} rybek`}</div><button class="primary pack-action" data-action="pack" ${progress.fish<PACK_COST&&!progress.freePack?"disabled":""}>Otevřít balíček</button><button class="odds-toggle" data-action="odds">${showOdds?"Skrýt pravděpodobnosti":"Zobrazit pravděpodobnosti"}</button><div class="odds ${showOdds?"visible":""}"><span>Běžná <b>60 %</b></span><span>Vzácná <b>25 %</b></span><span>Epická <b>10 %</b></span><span>Legendární <b>4 %</b></span><span>Mýtická <b>1 %</b></span><span>Shiny <b>1 %</b></span></div><button class="diamond secondary" data-action="diamond-pack" ${progress.diamonds<GAME_CONFIG.packDiamondCost?"disabled":""}>Diamantová schránka · 25</button></section>`;}
function deployedView(card:BattleCard|DeckCard,used=false,enemy=false){const c=catById(card.catId)!;return `<div class="deployed ${used?"used":""}"><small>${enemy?"SOUPEŘOVA":"TVÁ"} NASAZENÁ KOČKA</small>${art(c,false,card.shiny)}<b>${c.name}</b><span>${c.element} · ${c.rarity} · ${used?"Použita":"Připravena"}</span></div>`;}
function arena(){if(!duel){const valid=progress.starterDeckActive||validateDeck(progress.deck,progress.collection).valid;return `<section class="arena"><p class="kicker">ELEMENTÁRNÍ DUEL</p><h1>Aréna Sedmi tlapek</h1><p>První se třemi vítězstvími vyhrává. Nejvýše sedm kol.</p>${progress.deployed?deployedView({...progress.deployed,uid:"preview"}):'<div class="notice">Vyber nasazenou kočku.</div>'}<button class="primary" data-action="start-duel" ${!valid||!progress.deployed?"disabled":""}>Vstoupit do arény</button>${!valid?'<div class="notice">Balíček musí mít 20 platných karet.</div>':""}</section>`;}
  const last=duel.history.at(-1);return `<section class="arena battle"><div class="enemy-head"><b>Strážce Mlžných tlapek</b><span>${duel.opponent.wins} : ${duel.player.wins}</span><small>Ruka ${duel.opponent.hand.length} · Balíček ${duel.opponent.drawPile.length}</small></div>${deployedView(duel.opponent.deployed,duel.opponent.deployedUsed,true)}${last?`<div class="clash"><b>${catById(last.playerCard.catId)?.name} ${last.playerPower.final}</b><i>VS</i><b>${last.opponentPower.final} ${catById(last.opponentCard.catId)?.name}</b><small>${last.winner==="player"?"Vyhráváš kolo":last.winner==="opponent"?"Soupeř vyhrává kolo":"Kolo je remíza"}</small><small>${last.playerPower.reasons.join(" · ")}</small></div>`:`<div class="clash">Kolo ${duel.round}: vyber kočku</div>`}${duel.finished?`<div class="notice"><h2>${duel.winner==="player"?"Vítězství!":duel.winner==="opponent"?"Prohra":"Remíza"}</h2><button class="primary" data-action="finish-duel">Převzít odměnu</button></div>`:`<div class="hand">${duel.player.hand.map(b=>card(catById(b.catId)!,"battle",b)).join("")}</div>${!duel.player.deployedUsed?`<button class="deployed-play" data-play="${duel.player.deployed.uid}">Zahrát nasazenou kočku</button>`:""}<div class="pile-info">Ruka ${duel.player.hand.length}/${duel.player.handLimit} · Balíček ${duel.player.drawPile.length} · Odhozeno ${duel.player.discard.length}</div>`}${deployedView(duel.player.deployed,duel.player.deployedUsed)}</section>`;}
function nav(){return `<nav>${(["island","cats","packs","arena"] as const).map(n=>`<button data-nav="${n}" class="${screen===n?"active":""}"><i><img src="${icons[n]}" alt=""/></i>${{island:"Ostrov",cats:"Kočky",packs:"Schránky",arena:"Aréna"}[n]}</button>`).join("")}</nav>`;}
function render(){const detail=selectedCatId?catById(selectedCatId):null;app.className=duel?"duel-active":"";app.innerHTML=`${header()}<main>${screen==="island"?island():screen==="cats"?cats():screen==="packs"?packs():arena()}</main>${duel?duel.finished?"":`<div class="duel-action"><button class="primary" data-action="confirm-card" ${selectedBattleUid?"":"disabled"}>Zahrát vybranou kartu</button></div>`:nav()}${detail?`<div class="detail-modal"><div><button class="detail-close" data-close-detail aria-label="Zavřít">×</button>${art(detail)}<p class="kicker">${detail.rarity} · ${detail.element}</p><h2>${detail.name}</h2><p>Síla ${detail.power} · Level ${progress.collection[detail.id]?.level||1}</p><p>${detail.passive}</p><button class="secondary" data-close-detail>Zavřít detail</button></div></div>`:""}${!progress.tutorialDone?`<div class="modal"><div>${art(CATS[2]!)}<p class="kicker">VÍTEJ V MEOWVERSE</p><h2>Jsem Lístka, tvá průvodkyně.</h2><p>Dávám ti dočasný balíček 20 karet, aby sis mohl hned vyzkoušet arénu.</p><button class="primary" data-action="tutorial">Začít dobrodružství</button></div></div>`:""}`;bindStable();}
function persist(){saveProgress(progress);render();}
function addCard(id:string){const cat=catById(id)!,owned=progress.collection[id];if(!owned)return;const used=progress.deck.filter(c=>c.catId===id).length;if(progress.deck.length>=20||used>=GAME_CONFIG.copyLimits[cat.rarity]||used>=owned.normal+owned.shiny)return;const normalUsed=progress.deck.filter(c=>c.catId===id&&!c.shiny).length;const shiny=normalUsed>=owned.normal&&owned.shiny>0;progress={...progress,starterDeckActive:false,deck:[...progress.deck,{catId:id,shiny}]};persist();}
function removeCard(id:string){const index=progress.deck.map(c=>c.catId).lastIndexOf(id);if(index<0)return;progress={...progress,starterDeckActive:false,deck:progress.deck.filter((_,i)=>i!==index)};persist();}
function openPack(diamond=false){if(opening)return;const paid=diamond?buyDiamondPack(progress):buyPack(progress,progress.freePack);if(!paid)return;opening=true;const rarity:Rarity=diamond?rollDiamondRarity(Math.random()):rollRarity(Math.random());const pool=CATS.filter(c=>c.rarity===rarity);const cat=pool[Math.floor(Math.random()*pool.length)]!;const shiny=rollShiny(Math.random(),diamond?GAME_CONFIG.diamondShinyChance:GAME_CONFIG.shinyChance);const current=paid.collection[cat.id]||defaultOwned(cat.id);progress={...paid,collection:{...paid.collection,[cat.id]:{...current,[shiny?"shiny":"normal"]:current[shiny?"shiny":"normal"]+1}}};saveProgress(progress);const modal=document.createElement("div");modal.className=`pack-sequence rarity-${rarity.toLowerCase()} ${shiny?"shiny-reveal":""}`;modal.innerHTML=`<div class="sequence-stage"><p class="kicker">KOČIČÍ SCHRÁNKA PŘILETĚLA</p><img class="sequence-chest" src="${assets.packs.chest}" alt="Kočičí schránka"/><button class="paw-lock"><img src="${assets.ui.paw}" alt=""/>Podrž tlapkový zámek</button><small>Světlo ze schránky sílí…</small></div>`;app.append(modal);requestAnimationFrame(()=>modal.classList.add("landed"));const lock=modal.querySelector<HTMLButtonElement>(".paw-lock")!;const reveal=()=>{if(modal.classList.contains("opening"))return;modal.classList.add("opening");navigator.vibrate?.([40,30,70]);setTimeout(()=>{modal.className=`reveal shown ${rarity.toLowerCase()} ${shiny?"shiny-reveal":""}`;modal.innerHTML=`<div><p class="kicker">${shiny?"✦ SHINY · ":""}${rarity.toUpperCase()}</p>${art(cat,false,shiny)}<h2>${cat.name}</h2><p>${cat.element} · Síla ${cat.power}</p><small>${shiny?current.shinyPassive:cat.passive}</small><button class="primary">Pokračovat</button></div>`;modal.querySelector("button")!.addEventListener("click",()=>{opening=false;render();});},850);};lock.addEventListener("pointerdown",reveal);lock.addEventListener("click",reveal);}
function startBattle(){if(!progress.deployed)return;const deck=progress.starterDeckActive?starterDeck():progress.deck;const enemyDeck=Array.from({length:20},(_,i)=>({catId:CATS[i%CATS.length]!.id,shiny:i===0}));duel=startDuel(deck,progress.deployed,progress.collection,enemyDeck,{catId:"marena",shiny:false},enemyCollection);render();}
function play(uid:string){if(!duel||duel.finished)return;duel=playRound(duel,uid,chooseOpponentCard(duel),progress.collection,enemyCollection);render();}
function finishBattle(){if(!duel?.winner)return;progress=awardDuel(progress,duel.winner==="player"?"win":duel.winner==="opponent"?"loss":"draw");duel=null;persist();}
function bind(){document.querySelectorAll<HTMLElement>("[data-nav]").forEach(e=>e.onclick=()=>{screen=e.dataset.nav!;render();});document.querySelector(".logo")?.addEventListener("click",()=>{const now=Date.now();logoTaps=logoTaps.filter(t=>now-t<1800);logoTaps.push(now);if(logoTaps.length>=5)location.href="/legacy/";});document.querySelectorAll<HTMLElement>("[data-building]").forEach(e=>e.addEventListener("pointerdown",()=>{e.classList.add("building-tapped");setTimeout(()=>e.classList.remove("building-tapped"),450)}));const world=document.querySelector<HTMLElement>("[data-parallax]");world?.addEventListener("pointermove",e=>{const r=world.getBoundingClientRect();world.style.setProperty("--px",`${(e.clientX-r.left)/r.width-.5}`);world.style.setProperty("--py",`${(e.clientY-r.top)/r.height-.5}`)});document.querySelector('[data-action="collect"]')?.addEventListener("click",()=>{progress=collectPond(progress);navigator.vibrate?.(20);persist();});document.querySelector('[data-action="tutorial"]')?.addEventListener("click",()=>{progress={...progress,tutorialDone:true};persist();});document.querySelectorAll('[data-action="pack"]').forEach(e=>e.addEventListener("click",()=>openPack(false)));document.querySelector('[data-action="diamond-pack"]')?.addEventListener("click",()=>openPack(true));document.querySelector('[data-action="start-duel"]')?.addEventListener("click",startBattle);document.querySelector('[data-action="finish-duel"]')?.addEventListener("click",finishBattle);document.querySelectorAll<HTMLElement>("[data-add]").forEach(e=>e.onclick=()=>addCard(e.dataset.add!));document.querySelectorAll<HTMLElement>("[data-remove]").forEach(e=>e.onclick=()=>removeCard(e.dataset.remove!));document.querySelectorAll<HTMLElement>("[data-deploy]").forEach(e=>e.onclick=()=>{progress={...progress,deployed:{catId:e.dataset.deploy!,shiny:false}};persist();});document.querySelectorAll<HTMLElement>("[data-play]").forEach(e=>{let timer=0,peeked=false;e.addEventListener("pointerdown",()=>{peeked=false;timer=window.setTimeout(()=>{peeked=true;e.classList.add("peek")},450)});e.addEventListener("pointerup",()=>{clearTimeout(timer);setTimeout(()=>e.classList.remove("peek"),180)});e.addEventListener("pointercancel",()=>clearTimeout(timer));e.onclick=event=>{if(peeked){event.preventDefault();peeked=false;return}play(e.dataset.play!)};});}
function bindStable(){
  document.querySelectorAll<HTMLElement>("[data-nav]").forEach(e=>e.onclick=()=>{screen=e.dataset.nav!;selectedCatId=null;render();});
  document.querySelector(".logo")?.addEventListener("click",()=>{const now=Date.now();logoTaps=logoTaps.filter(t=>now-t<1800);logoTaps.push(now);if(logoTaps.length>=5)location.href="/legacy/";});
  document.querySelectorAll<HTMLElement>("[data-building]").forEach(e=>e.onclick=event=>{event.stopPropagation();selectedBuilding=e.dataset.building!;e.classList.add("building-tapped");render();});
  document.querySelector("[data-island-world]")?.addEventListener("click",event=>{if(event.target===event.currentTarget){selectedBuilding=null;render();}});
  document.querySelectorAll<HTMLElement>("[data-cats-mode]").forEach(e=>e.onclick=()=>{catsMode=e.dataset.catsMode as "collection"|"deck";render();});
  document.querySelectorAll<HTMLElement>("[data-cat]").forEach(e=>e.onclick=()=>{if(progress.collection[e.dataset.cat!]){selectedCatId=e.dataset.cat!;render();}});
  document.querySelectorAll<HTMLElement>("[data-close-detail]").forEach(e=>e.onclick=()=>{selectedCatId=null;render();});
  document.querySelector('[data-action="collect"]')?.addEventListener("click",()=>{progress=collectPond(progress);navigator.vibrate?.(20);persist();});
  document.querySelector('[data-action="tutorial"]')?.addEventListener("click",()=>{progress={...progress,tutorialDone:true};persist();});
  document.querySelector('[data-action="pack"]')?.addEventListener("click",()=>openPack(false));
  document.querySelector('[data-action="odds"]')?.addEventListener("click",()=>{showOdds=!showOdds;render();});
  document.querySelector('[data-action="diamond-pack"]')?.addEventListener("click",()=>openPack(true));
  document.querySelector('[data-action="start-duel"]')?.addEventListener("click",startBattle);
  document.querySelector('[data-action="finish-duel"]')?.addEventListener("click",finishBattle);
  document.querySelector('[data-action="confirm-card"]')?.addEventListener("click",()=>{if(selectedBattleUid){play(selectedBattleUid);selectedBattleUid=null;}});
  document.querySelectorAll<HTMLElement>("[data-add]").forEach(e=>e.onclick=()=>addCard(e.dataset.add!));
  document.querySelectorAll<HTMLElement>("[data-remove]").forEach(e=>e.onclick=()=>removeCard(e.dataset.remove!));
  document.querySelectorAll<HTMLElement>("[data-deploy]").forEach(e=>e.onclick=()=>{progress={...progress,deployed:{catId:e.dataset.deploy!,shiny:false}};persist();});
  document.querySelectorAll<HTMLElement>("[data-play]").forEach(e=>{let timer=0,peeked=false;e.addEventListener("pointerdown",()=>{timer=window.setTimeout(()=>{peeked=true;e.classList.add("peek")},450)});e.addEventListener("pointerup",()=>{clearTimeout(timer);setTimeout(()=>e.classList.remove("peek"),180)});e.onclick=event=>{if(peeked){event.preventDefault();peeked=false;return}selectedBattleUid=e.dataset.play!;render();};});
}
window.addEventListener("error",()=>{app.innerHTML='<div class="fatal"><h1>Kočičí zádrhel</h1><p>Obnov stránku a zkus to znovu.</p></div>';});
async function boot(){await Promise.allSettled(preloadAssets.map(src=>new Promise<void>(resolve=>{const image=new Image();const timer=window.setTimeout(resolve,2500);image.onload=image.onerror=()=>{clearTimeout(timer);resolve();};image.src=src})));render();if(import.meta.env.PROD&&"serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js");}
void boot();
