import {GAME_CONFIG} from "./config";
import {CATS,catById} from "./data/cats";
import {assets,catAsset} from "./data/assetManifest";
import {awardBattle,buyPack,collectPond,pondProduced,upgradePond} from "./core/economy";
import {resolveBattle} from "./core/duel";
import {freshProgress,loadProgress,saveProgress,STORAGE_KEY} from "./core/storage";
import type {Assignment,Cat} from "./types";

const app=document.querySelector<HTMLDivElement>("#app")!;
let progress=loadProgress(localStorage.getItem(STORAGE_KEY));
let logoTaps:number[]=[];let battleCatId:string|null=null;let opponentId="listka";let battleMessage="Vyber kočku. Element rozhoduje před silou.";
const icon=assets.icons;
const catArt=(cat:Cat,small=false)=>`<img class="cat-image ${small?"small":""}" src="${catAsset(cat.id)}" alt="${cat.name}" draggable="false">`;
const elementIcon=(element:Cat["element"])=>element==="Oheň"?"🔥":element==="Voda"?"💧":"🌿";
const ownedCats=()=>CATS.filter(cat=>progress.collection[cat.id]);
const assigned=(assignment:Assignment)=>ownedCats().filter(cat=>progress.collection[cat.id]?.assignment===assignment);
function header(){return `<header><button class="logo">MEOW<span>VERSE</span></button><div class="currency"><span><img src="${icon.fish}" alt="">${progress.fish}</span><span>🏅 ${progress.medals}</span><span><img src="${icon.diamond}" alt="">${progress.diamonds}</span></div></header>`;}
function quest(){const steps=["Posbírej rybky","Vylepši rybník","Otevři první balíček","Rozhodni o nové kočce","Vyhraj PvP souboj"];const step=Math.min(progress.tutorialStep,4);return `<div class="quest"><small>PRVNÍ DOBRODRUŽSTVÍ · ${step+1}/5</small><b>${steps[step]}</b><i style="--done:${step/5*100}%"></i></div>`;}
function island(){const fish=pondProduced(progress);return `<main class="island-screen">${quest()}<section class="island-world"><div class="island-ground"><button class="building pond" data-open="pond"><img src="${assets.buildings.pond}" alt="Rybník"><b>Rybník · ${fish}</b></button><button class="building home" data-open="pack"><img src="${assets.buildings.home}" alt="Kočičí domek"><b>Balíček</b></button><button class="building arena" data-open="arena"><img src="${assets.buildings.arena}" alt="Aréna"><b>Aréna</b></button>${assigned("pond").map((cat,index)=>`<div class="working-cat worker-${index}">${catArt(cat,true)}<span>chytá rybky</span></div>`).join("")}${assigned("pvp").map((cat,index)=>`<div class="walking-cat walker-${index}">${catArt(cat,true)}</div>`).join("")}</div></section><div class="island-help">Klepni na budovu</div></main>`;}
function pondScreen(){const fish=pondProduced(progress);const canUpgrade=progress.pondLevel<2&&progress.fish>=GAME_CONFIG.pondUpgradeCost;return `<main class="single-screen"><button class="back">← Ostrov</button><img class="hero-building" src="${assets.buildings.pond}" alt="Rybník"><p class="eyebrow">RYBNÍK · ÚROVEŇ ${progress.pondLevel}</p><h1>${fish} rybek čeká</h1><p>${assigned("pond").length?"Kapka pracuje: produkce +40 %.":"Přiřaď rybáře pro bonus +40 %."}</p>${fish>0?`<button class="primary" data-action="collect">Posbírat ${fish} rybek</button>`:progress.pondLevel<2?`<button class="primary" data-action="upgrade" ${canUpgrade?"":"disabled"}>Vylepšit za ${GAME_CONFIG.pondUpgradeCost} rybek</button>`:`<button class="primary" disabled>Rybník je vylepšený</button>`}<small class="hint">${fish>0?"Nejdřív vyzvedni úlovek.":canUpgrade?"Větší rybník vyrábí dvakrát rychleji.":"Potřebuješ více rybek."}</small></main>`;}
function packScreen(){const canBuy=progress.fish>=GAME_CONFIG.packCost;return `<main class="single-screen pack-screen"><button class="back">← Ostrov</button><p class="eyebrow">KOČIČÍ BALÍČEK</p><h1>Nový parťák čeká</h1><img class="pack-image" src="${assets.packs.chest}" alt="Kočičí balíček"><button class="primary" data-action="pack" ${canBuy?"":"disabled"}>Otevřít · ${GAME_CONFIG.packCost} rybek</button><small class="hint">Obsah: 1 nová kočka. Každá má stejnou šanci.</small></main>`;}
function assignmentScreen(){const cat=catById(progress.pendingCatId||"")!;return `<main class="choice-screen"><p class="eyebrow">NOVÁ KOČKA</p>${catArt(cat)}<h1>${cat.name}</h1><div class="cat-facts"><span>${elementIcon(cat.element)} ${cat.element}</span><span>⚡ Síla ${cat.power}</span><span>🛠 ${cat.profession}</span></div><h2>Kam ji pošleš?</h2><div class="choice-actions"><button data-assign="pond"><b>🎣 Pracovat</b><small>${cat.profession==="Rybář"?"Rybník +40 %":"V rybníku bez bonusu"}</small></button><button data-assign="pvp"><b>⚔️ Do PvP</b><small>${cat.element} · síla ${cat.power}</small></button></div><p class="decision-note">Kočka může být jen na jednom místě. Později ji můžeš přeřadit.</p></main>`;}
function arenaScreen(){const cats=assigned("pvp");const opponent=catById(opponentId)!;return `<main class="arena-screen"><button class="back">← Ostrov</button><p class="eyebrow">ARÉNA</p><h1>Vyber bojovníka</h1><div class="rules"><span>🔥 &gt; 🌿</span><span>🌿 &gt; 💧</span><span>💧 &gt; 🔥</span></div><div class="enemy"><small>SOUPĚŘ</small>${catArt(opponent,true)}<b>${opponent.name}</b><span>${elementIcon(opponent.element)} ${opponent.element} · ⚡ ${opponent.power}</span></div><div class="battle-message">${battleMessage}</div><div class="fighter-row">${cats.map(cat=>`<button class="fighter ${battleCatId===cat.id?"selected":""}" data-fighter="${cat.id}">${catArt(cat,true)}<b>${cat.name}</b><small>${elementIcon(cat.element)} · ${cat.power}</small></button>`).join("")||"<p>Nejdřív pošli kočku do PvP.</p>"}</div><button class="primary" data-action="fight" ${battleCatId?"":"disabled"}>Bojovat</button><small class="hint">Výhra: 2 medaile a 8 rybek</small></main>`;}
function revealPack(){const available=CATS.filter(cat=>!progress.collection[cat.id]);const cat=available[0]||CATS[Math.floor(Math.random()*CATS.length)]!;progress={...progress,collection:{...progress.collection,[cat.id]:{count:(progress.collection[cat.id]?.count||0)+1,assignment:null}},pendingCatId:cat.id,tutorialStep:3};saveProgress(progress);app.innerHTML=`<div class="reveal"><div><p class="eyebrow">NOVÁ KOČKA!</p>${catArt(cat)}<h1>${cat.name}</h1><p>${elementIcon(cat.element)} ${cat.element} · ⚡ ${cat.power} · ${cat.profession}</p><button class="primary" data-reveal-next>Rozhodnout o kočce</button></div></div>`;app.querySelector<HTMLElement>("[data-reveal-next]")!.onclick=()=>{screen="choice";render();};}
let screen=progress.pendingCatId?"choice":"island";
function render(){app.innerHTML=header()+(screen==="island"?island():screen==="pond"?pondScreen():screen==="pack"?packScreen():screen==="choice"?assignmentScreen():arenaScreen());bind();}
function bind(){app.querySelector(".logo")?.addEventListener("click",()=>{const now=Date.now();logoTaps=logoTaps.filter(t=>now-t<1800);logoTaps.push(now);if(logoTaps.length>=5)location.href="/legacy/";});app.querySelectorAll<HTMLElement>("[data-open]").forEach(el=>el.onclick=()=>{screen=el.dataset.open!;render();});app.querySelector(".back")?.addEventListener("click",()=>{screen="island";battleMessage="Vyber kočku. Element rozhoduje před silou.";render();});app.querySelector<HTMLElement>("[data-action=collect]")?.addEventListener("click",()=>{progress=collectPond(progress);saveProgress(progress);render();});app.querySelector<HTMLElement>("[data-action=upgrade]")?.addEventListener("click",()=>{const next=upgradePond(progress);if(next){progress=next;saveProgress(progress);screen="pack";render();}});app.querySelector<HTMLElement>("[data-action=pack]")?.addEventListener("click",()=>{const next=buyPack(progress);if(next){progress=next;revealPack();}});app.querySelectorAll<HTMLElement>("[data-assign]").forEach(el=>el.onclick=()=>{const id=progress.pendingCatId!;progress={...progress,collection:{...progress.collection,[id]:{...progress.collection[id]!,assignment:el.dataset.assign as Assignment}},pendingCatId:null,tutorialStep:4};saveProgress(progress);screen=el.dataset.assign==="pvp"?"arena":"island";render();});app.querySelectorAll<HTMLElement>("[data-fighter]").forEach(el=>el.onclick=()=>{battleCatId=el.dataset.fighter!;render();});app.querySelector<HTMLElement>("[data-action=fight]")?.addEventListener("click",()=>{const player=catById(battleCatId!)!;const opponent=catById(opponentId)!;const result=resolveBattle(player,opponent);const win=result.winner==="player";progress=awardBattle(progress,win,win&&player.id==="kapka"?3:0,win&&player.id==="jiskra"?1:0);progress={...progress,tutorialStep:5};saveProgress(progress);battleMessage=`${win?"Vítězství!":"Prohra."} ${result.reason}`;opponentId=opponentId==="listka"?"kapka":"listka";battleCatId=null;render();});}
window.addEventListener("error",event=>{console.error(event.error);app.innerHTML='<div class="fatal"><h1>Kočičí zádrhel</h1><button onclick="location.reload()">Zkusit znovu</button></div>';});render();Object.assign(window,{resetMeowVerse:()=>{progress=freshProgress();saveProgress(progress);location.reload();}});
